# Generated by Django 3.2 on 2023-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='website.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='articles_old', through='website.ArticleTag', to='website.Tag'),
        ),
    ]
